name:                yorgey-cis194
version:             0.1.0.0
synopsis:            "Brent Yorgey CIS 194: Introduction to Haskell (Spring 2013)"
description:         "Please see the README on GitHub at <https://github.com/erlnow/yorge-cis194#readme>"
# homepage:            https://github.com/erlnow/yorgey-cis194#readme
# -- bug-reports:
github:              "erlnow/yorgey-cis194"
license:             BSD3
license-file:        LICENSE
author:              Eduardo Ramón Lestau
maintainer:          erlestau@gmail.com
copyright:           "(c) 2020-2030 Eduardo Ramón Lestau"
category:            Learning
build-type:          Simple

# verbatim:
#   cabal-version:     >=1.10

extra-source-files:  
  - CHANGELOG.md
  - README.md
  - doc/*

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  -Wall

library:
  source-dirs: src

executables:
  cabal-sample:
    source-dirs: app
    main: Main.hs
    dependencies:
      - yorgey-cis194
    ghc-options:
      -threaded
      -rtsopts
      -with-rtsopts=-N

tests:
  cabal-sample-test:
    main: MyLibTest.hs
    source-dirs: test
    ghc-options:
      -threaded
      -rtsopts
      -with-rtsopts=-N
    dependencies:
      - yorgey-cis194
        #      - QuickCheck
        #build-tools: hspec-discover
